dist: bionic
language: ruby
cache: bundler
before_install:
- bundle -v
- rm -f Gemfile.lock
- gem update --system $RUBYGEMS_VERSION
- gem --version
- bundle -v
script:
- bundle exec rake $CHECK
rvm:
- 2.5.3
stages:
- static
- spec
- name: deploy
  if: tag =~ ^v\d
jobs:
  fast_finish: true
  include:
  - stage: static
    bundler_args: "--without system_tests"
    env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"

  - stage: spec
    bundler_args: "--without system_tests"
    env: PUPPET_GEM_VERSION="~> 6.0" CHECK="parallel_spec spec/classes spec/defines"

  - stage: deploy
    bundler_args: "--without system_tests"
    env: CHECK=build DEPLOY_TO_FORGE=yes

branches:
  only:
  - master
  - "/^v\\d/"
notifications:
  email: false
deploy:
  provider: puppetforge
  user: maeq
  password:
    secure: "ZkUGyvVbAeCWpuXEGYrHuudwzapTQbe9yOrqdI/cakl3/qJPECbT0GpHTdPMzIzn32LchRiO+IH0OqkGMlkYFMQszE0L1L2AmFaMhL69I2kYxec5TFN5Xz31ALlvqGYV433aarGbL9i8LAixwPFSYVNE6uYyf3ZFEs0pyBwda4I0ZCF6t+HAHA5qiCzmW9vh2YO0BJ/cOSFIUNTQ44BMlH1gC3xuzBsINbvRZQHnG+/PhURMyReOsQ9upPwAhTHa+wcb7sVyhlhWPhHvzEHoscPPO6XulgEjZArjxyTlqk6ghmCjc5pQI+/nkVyrJB3+l0MqFW8BVl/m6IxzmkeyPnvET6hGtLB56Abb5UmtEdtLvjJCswcsKuSFBDw5IgSim9K30d5VuOBOSbBEOe6MLNbzcBPaMEu0EEYphSGXmLPgykg1JGri8PhPi8zBMAJ3U6iVTAD34Hl3VYLJp35MblNEmJME/wQOXTunmSdcDR2l8oKSoqfIJ48gpChVphqCVU2L6N5U0bfZupHoNXeZ5deTOMiAOA+CXiG6lsmEuJCX3uchbcjcE3juTWe+RhTQqSFArlAKZgKpeCXtUgc4b88Ya6opqd+NLyM3R26d6wfHeT5DI+doYiwGRN/QKco/9WzMqzo1EjneRxnYHtagEavO9b2NiGGp6TdkmKPU4Q0="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
